from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from scripts.write_entity_graph_provenance import build_manifest, read_sources_file


def test_provenance_manifest_records_digest_and_metadata(tmp_path: Path) -> None:
    payload = b"legal-open-data-fixture\n"
    source = tmp_path / "input.bin"
    source.write_bytes(payload)

    manifest = build_manifest(
        tmp_path,
        [("https://example.test/input.bin", Path("input.bin"))],
        {
            "years": ["2024"],
            "parts_per_year": 4,
            "workflow_script": ".github/workflows/entity-graph.yml",
        },
    )

    assert manifest["schema_version"] == 1
    assert manifest["inputs"] == [
        {
            "path": "input.bin",
            "source_url": "https://example.test/input.bin",
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
        }
    ]
    assert manifest["build"]["years"] == ["2024"]


def test_sources_file_ignores_comments_and_blank_lines(tmp_path: Path) -> None:
    sources = tmp_path / "sources.tsv"
    sources.write_text(
        "# generated by workflow\n\nhttps://example.test/a=a.bin\n"
        "https://example.test/b=b.bin\n",
        encoding="utf-8",
    )

    assert read_sources_file(sources) == [
        ("https://example.test/a", Path("a.bin")),
        ("https://example.test/b", Path("b.bin")),
    ]


def test_sources_file_reports_line_number_for_invalid_entry(tmp_path: Path) -> None:
    sources = tmp_path / "sources.tsv"
    sources.write_text("https://example.test/a=a.bin\ninvalid\n", encoding="utf-8")

    with pytest.raises(ValueError, match=r"sources\.tsv:2:.*URL=PATH"):
        read_sources_file(sources)


def test_provenance_rejects_duplicate_paths(tmp_path: Path) -> None:
    source = tmp_path / "input.bin"
    source.write_bytes(b"fixture")

    with pytest.raises(ValueError, match="duplicate provenance input path"):
        build_manifest(
            tmp_path,
            [
                ("https://example.test/a", Path("input.bin")),
                ("https://example.test/b", Path("input.bin")),
            ],
            {},
        )


def test_provenance_rejects_missing_inputs(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError, match="provenance input is missing"):
        build_manifest(
            tmp_path,
            [("https://example.test/missing", Path("missing.bin"))],
            {},
        )


def test_manifest_is_json_serializable(tmp_path: Path) -> None:
    source = tmp_path / "input.json"
    source.write_text('{"ok": true}\n', encoding="utf-8")

    manifest = build_manifest(
        tmp_path,
        [("https://example.test/input.json", Path("input.json"))],
        {"years": ["2024", "2025", "2026"], "parts_per_year": 4},
    )

    json.dumps(manifest, ensure_ascii=False, sort_keys=True)
